---
- name: "wait 300 seconds"
  wait_for_connection:
          delay: 5
          sleep: 5
          timeout: 300


- name: "Install command packages"
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
          - apache2
  become: yes



- name: "enable service"
  service:
          name: apache2
          enabled: yes
  become: yes



- name: " restart service"
  service:
          name: apache2
          enabled: yes

  become: true


#- name: "add firewalld rule"
#  firewalld:
#          port: "8080/tcp"
#          permanent: yes
#          state: enabled
#          immediate: yes
#  notify: "restart firewalld"
#  become: true
